default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  username: postgres

development:
  <<: *default
  database: resit_boilerplate_dev

test:
  <<: *default
  database: db

production:
  adapter: postgresql
  database: resit_boilerplate_production
  pool: 5
  host: resit_boilerplate_app-db
  username: resit_boilerplate_user
  password: password
